# Site settings
description: A blog from the Ritter Insurance Marketing Software development department, a.k.a. RIMdev
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://rimdev.io
enforce_ssl: rimdev.io
rim_copy: Ritter Insurance Marketing LLC
rim_url: https://ritterim.com
rim_blog: https://ritterim.com/blog/
map_url: https://www.google.com/maps/place/2605+Interstate+Dr,+Harrisburg,+PA+17110/@40.311543,-76.8473254,17z/data=!3m1!4b1!4m5!3m4!1s0x89c8c76bd2816303:0x213d7b96bee1d959!8m2!3d40.311543!4d-76.8451367?hl=en
default_image: /images/default/rimdev-surface.jpg
safe: false
title: RIMdev Technical Blog

# Font Awesome version
fa_version: 4.6.0

# Build settings
timezone: America/New_York
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
# sitemap: false in front matter of page to exclude
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# will convert @twitter-handle to the full twitter link in a post
jekyll-mentions: https://twitter.com

# User settings
username: RIMdev
user_description: Ritter Insurance Marketing | Software DEVelopment
user_title: RIMdev
user_logo: /assets/img/logos/RIMdev-logo-text-white.svg
user_icon: /assets/img/logos/RIMdev-icon-white.svg
email: anon@ritterim.com
twitter_username: ritterim
github_username:  ritterim
disqus_username: rimdev

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Url Shortener
shortener:
  basepath: /s/        # Path for stored redirects.
  preserve: false      # Keep previously generated files.
  salt:     "RimDev"   # The optional salt, used when hasing the Unix time.

# Feed
feed:
  path: feed.xml

# RIMdev posting authors
RIMdev:
  Bill Boga:
    avatar: https://avatars2.githubusercontent.com/u/3382469?v=3
    title: Senior Software Developer
    desc: Polyglot with focus on C#. Also enjoy building and tinkering with hardware.
    twitter: billbogaiv
    github: billbogaiv
  Tom Harold:
    avatar: https://avatars3.githubusercontent.com/u/4880437?v=3
    github: tgharold
  Kevin Hougasian:
    avatar: https://avatars2.githubusercontent.com/u/6231956?v=3
    title: Lead Frontend Developer
    twitter: hougasian
    github: hougasian
  Chad Peters:
    avatar: https://avatars3.githubusercontent.com/u/2921868?v=3
    github: lightyeare
  Scott Schwalm:
    avatar: https://avatars0.githubusercontent.com/u/3587144?v=3
    github: ScottSchwalm
  Beth Warner:
    avatar: https://avatars2.githubusercontent.com/u/1625929?v=3
    github: bwarner22
  Jaime Jones:
    avatar: https://avatars0.githubusercontent.com/u/24712731?v=4
    title: Lead Frontend Developer
    github: jaime-lynn
    twitter: gameof_freckles
  Andrew Rady:
    avatar: https://avatars1.githubusercontent.com/u/29714810?v=4
    title: Back End Developer
    github: andrewrady
    twitter: nodevemberJS
  John Vicari:
    avatar: https://avatars1.githubusercontent.com/u/10562755?v=4
    title: Sr. Front End Developer
    github: jpvicari
    twitter: johnvicari
  Kevin Ricords:
    avatar: https://avatars2.githubusercontent.com/u/7989792?s=460&v=4
    title: Sr. Database Developer
    github: kricords
  Cheng Yang:
    avatar: https://avatars3.githubusercontent.com/u/27984559?s=460&v=4
    title: Software Developer
    github: czy5074
    twitter: YangCzy50
  Ted Krueger:
    avatar: https://avatars0.githubusercontent.com/u/5313708?s=460&v=4
    title: UI/UX Developer
    github: tedk13
  Natasha Kurus:
    avatar: https://avatars0.githubusercontent.com/u/25621042?s=460&v=4
    title: UX/UI Developer
    github: natakurus
  Steliana Vassileva:
    avatar: https://avatars3.githubusercontent.com/u/41246417?v=4
    title: Documentation Specialist
    github: sdvassil
  # Previous Team Members
  #   Only Keep Individuals That
  #   Are Associated With Posts
  Seth Kline:
    avatar: https://avatars2.githubusercontent.com/u/21014591?s=460&v=4
    title: Frontend Developer (Former)
    github: sethkline
  Chidozie Oragwu:
    avatar: https://avatars3.githubusercontent.com/u/7084030?v=4
    title: Front End Developer (Former)
    github: alexoragz
    twitter: Chidonx
  Thomas Sobieck:
    avatar: https://avatars3.githubusercontent.com/u/6256765?s=88&v=4
    title: Sr. Software Developer (Former)
    github: sobieck
  Khalid Abuhakmeh:
    avatar: https://avatars0.githubusercontent.com/u/228256?v=3
    title: Director of Software Development (Former)
    desc: Focused on ASP.NET and Microsoft. Still love OSS &amp; Startups.
    twitter: buhakmeh
    github: khalidabuhakmeh
  Ken Dale:
    avatar: https://avatars3.githubusercontent.com/u/1012917?v=3
    title: Senior Application Developer (Former)
    twitter: kendaleiv
    github: kendaleiv
  Nathan White:
    avatar: https://avatars1.githubusercontent.com/u/4616177?v=3
    title: Frontend Developer (Former)
    desc:
    twitter: comfroels
    github: comfroels
    previous: true
  Ken Earl:
    avatar: https://avatars0.githubusercontent.com/u/1807843?v=3
    github: McKenjo
    title: Backend Developer (Former)
    previous: true
  Justin Rusbatch:
    title: Software Developer (Former)
    avatar: https://avatars0.githubusercontent.com/u/423549?v=3
    twitter: jrusbatch
    github: jrusbatch
    previous: true

ritter_links:
  - service: Ritter Insurance Marketing
    url: https://www.ritterim.com
  - service: Insurance Insider News by Craig Ritter
    url: https://blog.ritterim.com
  - service: Ritter Agent News
    url: https://www.ritterim.com/agentnews
  - service: Medicareful.com
    url: https://medicareful.com
